### ISSUE TITLE
Provide clarification text on Version Tab

### ISSUE THREAD

**Issue by bms63** [insightsengineering/r-pkgdown-multiversion#5]
A new user to admiral might be confused on the different versions of the website.  Providing some clarification text might help to mitigate this confusion.  

![image](https://user-images.githubusercontent.com/10111024/175568321-1699d824-9ad1-4946-b872-3d334575bc6d.png)

Perhaps 

* `main` - CRAN Released Package v0.7.0
* `devel` - Unreleased development version of Package

**Comment by bms63** [comment]
Also could main go on top?

**Comment by dinakar29** [comment]
So to summarize - there are 2 features being requested here:

1. The ability to add additional text or an alternate text in the dropdown menu for a given branch/tag
2. The ability to select a custom sort order of branches/tags in the dropdown (currently ascending)

Both are feasible. Will keep you posted after these have been implemented.

**Comment by dinakar29** [comment]
@bms63 Given the length of the text in the examples you provided, specifically:

* `main` - CRAN Released Package v0.7.0
* `devel` - Unreleased development version of Package

These might be too long for a dropdown menu. Would you prefer a tooltip that you can hover over to get that info? Or just plain text (will affect UI/UX elements)

**Comment by dinakar29** [comment]
Agreed, both would actually be nice.

**Comment by arkadiuszbeer** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/86738093/180429647-ee41c3f5-b95e-4693-b026-eaafc06bd96d.png)

**Comment by dinakar29** [comment]
@bms63 ☝ WDYT of this?

**Comment by cicdguy** [comment]
Feature's been merged. I'll begin testing this across repos.
FYI @bms63 this will be in `admiral.*` soon as all test cases succeed.
